name: project
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_text_to_speech: ^3.0.7
  google_maps_flutter: ^1.0.5


  cupertino_icons: ^1.0.2
  speech_to_text: ^3.1.0
  avatar_glow: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

